//存储当前用户
export const GET_CURRENT_USER = "GET_CURRENT_USER";
//登录
export const LOGIN_BEGIN = "LOGIN_BEGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
//注册
export const REGISTER_BEGIN = "REGISTER_BEGIN";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
//更新用户信息
export const UPDATE_INFO_BEGIN = "UPDATE_INFO_BEGIN";
export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS";
export const UPDATE_INFO_FAIL = "UPDATE_INFO_FAIL";
//更新密码
export const UPDATE_PWD_BEGIN = "UPDATE_PWD_BEGIN";
export const UPDATE_PWD_SUCCESS = "UPDATE_PWD_SUCCESS";
export const UPDATE_PWD_FAIL = "UPDATE_PWD_FAIL";
//获取购物数据
export const GET_STATICS_BEGIN = "GET_STATICS_BEGIN";
export const GET_STATICS_SUCCESS = "GET_STATICS_SUCCESS";
export const GET_STATICS_FAIL = "GET_STATICS_FAIL";

/**
 * 商品
 */

//商品详情
export const PRODUCT_DETAIL_BEGIN = "PRODUCT_DETAIL_BEGIN";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";
//加入购物车
export const ADD_TO_CART_BEGIN = "ADD_TO_CART_BEGIN";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
//根据购物车信息生成订单
export const GENERATEORDER_BEGIN = "GENERATEORDER_BEGIN";
export const GENERATEORDER_SUCCESS = "GENERATEORDER_SUCCESS";
export const GENERATEORDER_FAIL = "GENERATEORDER_FAIL";
//更新购物车单元
export const UPDATEATTR_BEGIN = "UPDATEATTR_BEGIN";
export const UPDATEATTR_SUCCESS = "UPDATEATTR_SUCCESS";
export const UPDATEATTR_FAIL = "UPDATEATTR_FAIL";
//获取SKU通过pid
export const GET_SKU_BY_PID_BEGIN = "GET_SKU_BY_PID_BEGIN";
export const GET_SKU_BY_PID_SUCCESS = "GET_SKU_BY_PID_SUCCESS";
export const GET_SKU_BY_PID_FAIL = "GET_SKU_BY_PID_FAIL";
//模糊查询商品
export const PRODUCT_SEARCH_BEGIN = "PRODUCT_SEARCH_BEGIN";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_FAIL = "PRODUCT_SEARCH_FAIL";

/**
 * 购物车
 */
//删除购物车单元
export const REMOVE_CART_ITEM_BEGIN = "REMOVE_CART_ITEM_BEGIN";
export const REMOVE_CART_ITEM_SUCCESS = "REMOVE_CART_ITEM_SUCCESS";
export const REMOVE_CART_ITEM_FAIL = "REMOVE_CART_ITEM_FAIL";

/**
 * 订单
 */
//获取订单通过uid
export const GET_ORDER_BY_UID_BEGIN = "GET_ORDER_BY_UID_BEGIN";
export const GET_ORDER_BY_UID_SUCCESS = "GET_ORDER_BY_UID_SUCCESS";
export const GET_ORDER_BY_UID_FAIL = "GET_ORDER_BY_UID_FAIL";
//获取订单单元By oid
export const GET_ORDER_ITEM_BY_OID_BEGIN = "GET_ORDER_ITEM_BY_OID_BEGIN";
export const GET_ORDER_ITEM_BY_OID_SUCCESS = "GET_ORDER_ITEM_BY_OID_SUCCESS";
export const GET_ORDER_ITEM_BY_OID_FAIL = "GET_ORDER_ITEM_BY_OID_FAIL";
//添加评价
export const ADD_COMMENT_BEGIN = "ADD_COMMENT_BEGIN";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";
//获取评价By orderItemId
export const GET_COMMENT_BEGIN = "GET_COMMENT_BEGIN";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAIL = "GET_COMMENT_FAIL";
//确认订单
export const CONFIRM_ORDER_BEGIN = "CONFIRM_ORDER_BEGIN";
export const CONFIRM_ORDER_SUCCESS = "CONFIRM_ORDER_SUCCESS";
export const CONFIRM_ORDER_FAIL = "CONFIRM_ORDER_FAIL";
//确认订单
export const GET_ORDER_COUNT_BEGIN = "GET_ORDER_COUNT_BEGIN";
export const GET_ORDER_COUNT_SUCCESS = "GET_ORDER_COUNT_SUCCESS";
export const GET_ORDER_COUNT_FAIL = "GET_ORDER_COUNT_FAIL";